# Generated by Django 3.1 on 2021-11-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211104_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Order',
            new_name='order',
        ),
    ]
